<?php


namespace A2nt\UserFormsPayments\Controllers;

use SilverStripe\Control\Controller;
use SilverStripe\Control\HTTPRequest;
use SilverStripe\Control\HTTPResponse;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\Form;
use SilverStripe\Forms\FormAction;
use SilverStripe\Forms\HiddenField;
use SilverStripe\Forms\RequiredFields;
use SilverStripe\Omnipay\GatewayFieldsFactory;
use SilverStripe\Omnipay\GatewayInfo;
use SilverStripe\Omnipay\Model\Payment;
use SilverStripe\Omnipay\Service\ServiceFactory;
use SilverStripe\UserForms\Model\Submission\SubmittedForm;

class UserFormsPaymentController extends \PageController
{
    private static $url_segment = '/userpayment';

    private static $allowed_actions = [
        'pay',
        'complete',
	    'canceled',
        'Form',
    ];

    private static $allowed_objects = [
        'SubmittedForm' => SubmittedForm::class,
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    private $object;

    protected function getShortPayableObjectName($class)
    {
        $allowed = self::$allowed_objects;
        return array_search($class, $allowed);
    }

    protected function getPayableObjectClass($short_name)
    {
        $allowed = self::$allowed_objects;
        return $allowed[$short_name];
    }

    public function getPayableObject($new_params = [])
    {
        if ($this->object) {
            return $this->object;
        }

        $allowed = self::$allowed_objects;

        $request = $this->getRequest();
        $params = array_merge($request->allParams(), $new_params);
        $class = $params['ID'];
        $ID = $params['OtherID'];

        if (!$ID || !$class || !array_key_exists($class, $allowed)) {
            return false;
        }

        $class = $this->getPayableObjectClass($class);
        $obj = $class::get()->byID($ID);

        if (!$obj) {
            return false;
        }

        $this->object = $obj;

        return $this->object;
    }

    public function complete(HTTPRequest $request)
    {
        die(__CLASS__.'_'.__FUNCTION__.' TEST#2!!!');
    }

    public function canceled(HTTPRequest $request)
    {
        die(__CLASS__.'_'.__FUNCTION__.' TEST#3!!!');
    }

    public function pay(HTTPRequest $request)
    {
        $obj = $this->getPayableObject();
        if (!$obj) {
            return $this->httpError(404);
        }

        /*$params = [
            'currency_code' => 'USD',
            'invoice' => '194-SDX',
            'item_name' => 'Purchase membership',
            'amount' => 30,
            'notify_url' => '',
            'custom' => '',
            'bn' => '',
            'business' => '',
            'return' => '',
            'cancel_return' => '',
            'rm' => 1,
            'cmd' => '_xclick',
        ];*/
        /*var_dump('https://www.paypal.com/cgi-bin/webscr/?'.http_build_query($params));
        die('aaa');
        $this->redirect('https://www.paypal.com/cgi-bin/webscr/?'.http_build_query($params));
*/

        /*if(!$obj) {
            return $this->httpError(404);
        }*/

        return $this->render();
    }

    protected function getGateway()
    {
        $gateways = GatewayInfo::getSupportedGateways();
        return array_keys($gateways)[0];
    }

    public function Form()
    {
        $obj = $this->getPayableObject();
        if (!$obj) {
            return $this->httpError(404);
        }

        $gateway = $this->getGateway();

        // direct payment processing
        switch ($gateway) {
            case 'PayPal_Express':
                $response = $this->processPayment($obj);
                $response->redirectOrRespond()->output();
                exit();
                return $response->redirectOrRespond();
                break;
        }

        $factory = GatewayFieldsFactory::create($gateway);
        $fields = $factory->getFields();

        $allowed = self::$allowed_objects;
        $class = $this->getShortPayableObjectName(get_class($obj));

        $fields->push(HiddenField::create('ID', $class));
        $fields->push(HiddenField::create('OtherID', $obj->getField('ID')));

        return Form::create(
            $this,
            'Form',
            $fields,
            FieldList::create(FormAction::create(
                'doSubmit',
                _t('Checkout.PayNow', 'Pay Now')
            )),
            RequiredFields::create(['ID', 'OtherID'])
        );
    }

    protected function processPayment($obj, $data = [])
    {
        $gateway = $this->getGateway();
        $payment = Payment::create()
            ->init($gateway, $obj->Amount, 'USD')
            ->setSuccessUrl($this->Link('complete').'/'.$this->getShortPayableObjectName(get_class($obj)).'/'.$obj->ID)
            ->setFailureUrl($this->Link('canceled').'/'.$this->getShortPayableObjectName(get_class($obj)).'/'.$obj->ID);
        $payment->write();

        $response = ServiceFactory::create()
            ->getService($payment, ServiceFactory::INTENT_PAYMENT)
            ->initiate($data);

        /* @var \SilverStripe\Omnipay\Service\ServiceResponse $response */
        return $response;
    }

    public function doSubmit($data, $form)
    {
        $obj = $this->getPayableObject($data);
        if (!$obj) {
            return $this->httpError(404);
        }

        $response = $this->processPayment($obj, $data);
        return $response->redirectOrRespond();
    }

    public function Link($action = null)
    {
        return Controller::join_links(self::$url_segment, $action);
    }

    public function DefaultContainer()
    {
        return 'container';
    }
}
