<?php


namespace A2nt\UserFormsPayments\Controllers;


use SilverStripe\Control\HTTPRequest;
use SilverStripe\Control\HTTPResponse;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\Form;
use SilverStripe\Forms\FormAction;
use SilverStripe\Omnipay\GatewayFieldsFactory;
use SilverStripe\UserForms\Model\Submission\SubmittedForm;

class UserFormsPaymentController extends \PageController
{
	private static $allowed_actions = [
		'pay',
	];

	private static $allowed_objects = [
		'SubmittedForm' => SubmittedForm::class,
	];

	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
	}

	public function pay(HTTPRequest $request)
	{
		$allowed = self::$allowed_objects;
		$params = $request->allParams();
		$class = $params['ID'];
		$ID = $params['OtherID'];

		if(!$ID || !$class || !array_key_exists($class, $allowed)) {
			return $this->httpError(404);
		}

		$class = $allowed[$class];
		$obj = $class::get()->byID($ID);

		/*if(!$obj) {
			return $this->httpError(404);
		}*/

		return $this->render();
	}

	public function Form()
    {
        $factory = GatewayFieldsFactory::create($gateway);

        return Form::create(
            $this,
            'Form',
            $factory->getFields(),
            FieldList::create(FormAction::create(
                'doSubmit',
                _t("Checkout.PayNow", 'Pay Now')
            ))
        );
    }

    public function DefaultContainer()
    {
    	return 'container';
    }
}