---
Name: a2nt-userdefinedforms-payments
After:
  - silverstripe-omnipay-legacy
  - omnipay-services
  - omnipay-routes
  - userformsconfig
---

DNADesign\ElementalUserForms\Model\ElementForm:
  test: 'AAA'

SilverStripe\UserForms\Model\UserDefinedForm:
  test: 'BBB'