---
Name: a2nt-userdefinedforms-payments
After:
  - silverstripe-omnipay-legacy
  - omnipay-services
  - omnipay-routes
  - userformsconfig
---
SilverStripe\UserForms\Model\Submission\SubmittedForm:
  summary_fields:
    - ID
    - Created
    - Amount
    - TotalPaid
  extensions:
    - SilverStripe\Omnipay\Extensions\Payable
    - A2nt\UserFormsPayments\Extensions\UserFormPaymentsForm

SilverStripe\Omnipay\Model\Payment:
  has_one:
    'SubmittedForm': SilverStripe\UserForms\Model\Submission\SubmittedForm

DNADesign\ElementalUserForms\Model\ElementForm:
  extensions:
    - A2nt\UserFormsPayments\Extensions\UserFormPayments

#SilverStripe\UserForms\Model\UserDefinedForm:
#  extensions:
#    - A2nt\UserFormsPayments\Extensions\UserFormPayments
#
# Rewrite has_one value of Payment Condition Rules
#A2nt\UserFormsPayments\Models\PaymentConditionRule:
#  has_one:
#    'Parent': SilverStripe\UserForms\Model\UserDefinedForm